export const links = [
    {
        name:'О нас',
        link:'/about'
    },
    {
        name:'Концепция',
        link:'/concept'
    },
    {
        name:'Сортировка',
        link:'/sorting'
    },
    {
        name:'Карта',
        link:'/map'
    },
    {
        name:'Зачем',
        link:'/socia-lvalue'
    },
    {
        name:'Услуги',
        link:'/services'
    },
    {
        name:'Контакты',
        link:'/contacts'
    },
    {
        name:'Магазин',
        link:'/shop'
    },
]